### ISSUE TITLE
Unknown item after upgrading

### ISSUE THREAD

**Issue by thomasrudin** [Lejo1/adv_keys#1]
Existing item "default:skeleton_key" is now undefined, any chance for a compat/upgrade path?
Ref: https://github.com/pandorabox-io/pandorabox.io/issues/101

**Comment by Lejo1** [comment]
I needed to unregister it.
I don‘t know if there is a way to delete the unknown items.

**Comment by thomasrudin** [comment]
fixed by #2
Another (proper?) approach would be to create a whole new key and leave the existing ones alone...

**Comment by Lejo1** [comment]
> Another (proper?) approach would be to create a whole new key and leave the existing ones alone...

Sadly this is not possible because default.can_interact_with_node() only checks for item.name == "default:key" and not group.key = 1
See https://github.com/minetest/minetest_game/blob/master/mods/default/functions.lua#L588

**Comment by Lejo1** [comment]
Fixed in #2
